### ISSUE TITLE
SQL Error when comparing databases

### ISSUE THREAD

**Issue by drjordan-ca** [eulerto/pgquarrel#30]
Eulerto,
I am trying to compare 2 databases.  One is a backup of the other before I made changes to it.  The backup has 761 tables and the new db has 656 and approximately 100 new foreign keys defined.  I have tried the comparison twice reversing which database was the from and to, and both times recieved the same error:

DEBUG number of security labels in sequence "public"."idct_lognotes_control_id_seq": 0
DEBUG number of security labels in sequence "public"."idct_lognotes_control_id_seq": 0
DEBUG sequence public.idct_office_location_NEW_office_id_seq: server1 server2
ERROR query failed: ERROR:  relation "public.idct_office_location_new_office_id_seq" does not exist
LINE 1: ...max_value, min_value, cache_value, is_cycled FROM public.idc...

Any assistance you can give would be greatly appreciated.

**Comment by eulerto** [comment]
@drjordan-ca Could you try again with this fix?

**Comment by drjordan-ca** [comment]
That worked great.  Thank you very much.
