### ISSUE TITLE
DROP of function with DEFAULT has syntax error.

### ISSUE THREAD

**Issue by esgibsondxc** [eulerto/pgquarrel#32]
The DROP statement generated when a function parameter has a DEFAULT causes a syntax error in the output script.  Encountered in postgresql 9.6

example
drop for foo(arg1 integer DEFAULT 1::integer) 

DROP FUNCTION foo(arg1 integer DEFAULT 1::integer);

Should be 

DROP FUNCTION foo(arg1 integer);

OR

DROP FUNCTION foo(integer);

**Comment by eulerto** [comment]
@esgibsondxc Could you test again?

**Comment by esgibsondxc** [comment]
Now the generated DROP FUNCTIONS look correct.
