### ISSUE TITLE
pgquarrel does not work with sequences in PostgreSQL v10

### ISSUE THREAD

**Issue by laurenz** [eulerto/pgquarrel#34]
Selecting from a sequence has changed in PostgreSQL v10.
There are fewer columns now than there used to be, because most of the information has been transferred to the new system catalog `pg_sequence`.

pgquarrel has a problem with that because it tries to get the information by selecting from the sequence.

**Comment by eulerto** [comment]
@laurenz Could you test with this new commit?

**Comment by laurenz** [comment]
Thank you, that works fine.
