### ISSUE TITLE
Fail installing pgquarrel in debian

### ISSUE THREAD

**Issue by grandegoiania** [eulerto/pgquarrel#37]
Tenho Debian 8.6 com postgresql 9.4.12 instalado via apt-get e cmake 3.0.2
Tentei instalar com os comandos:
git clone https://github.com/eulerto/pgquarrel.git
cd pgquarrel
cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/9.6/server .
make

após 76% aparece o seguinte erro:
[ 76%] Building C object CMakeFiles/pgquarrel.dir/src/sequence.c.o                                                                    
/root/scripts/pgquarrel/src/sequence.c: In function ‘dumpCreateSequence’:
/root/scripts/pgquarrel/src/sequence.c:324:45: error: ‘PG_INT16_MIN’ undeclared (first use in this function)
   if (!is_ascending && atoi(s->minvalue) == PG_INT16_MIN)
                                             ^
/root/scripts/pgquarrel/src/sequence.c:324:45: note: each undeclared identifier is reported only once for each function it appears in
/root/scripts/pgquarrel/src/sequence.c:326:44: error: ‘PG_INT16_MAX’ undeclared (first use in this function)
   if (is_ascending && atoi(s->maxvalue) == PG_INT16_MAX)
                                            ^
/root/scripts/pgquarrel/src/sequence.c:331:45: error: ‘PG_INT32_MIN’ undeclared (first use in this function)
   if (!is_ascending && atoi(s->minvalue) == PG_INT32_MIN)
                                             ^
/root/scripts/pgquarrel/src/sequence.c:333:44: error: ‘PG_INT32_MAX’ undeclared (first use in this function)
   if (is_ascending && atoi(s->maxvalue) == PG_INT32_MAX)
                                            ^
/root/scripts/pgquarrel/src/sequence.c:346:50: error: ‘PG_INT64_MIN’ undeclared (first use in this function)
   snprintf(bufmin, sizeof(bufmin), INT64_FORMAT, PG_INT64_MIN);
                                                  ^
/root/scripts/pgquarrel/src/sequence.c:347:50: error: ‘PG_INT64_MAX’ undeclared (first use in this function)
   snprintf(bufmax, sizeof(bufmax), INT64_FORMAT, PG_INT64_MAX);
                                                  ^
CMakeFiles/pgquarrel.dir/build.make:468: recipe for target 'CMakeFiles/pgquarrel.dir/src/sequence.c.o' failed
make[2]: *** [CMakeFiles/pgquarrel.dir/src/sequence.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/pgquarrel.dir/all' failed
make[1]: *** [CMakeFiles/pgquarrel.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eulerto** [comment]
@grandegoiania could you test if this commit solved the issue?

**Comment by grandegoiania** [comment]
It worked, thanks.
