### ISSUE TITLE
compare only specific schema

### ISSUE THREAD

**Issue by grandegoiania** [eulerto/pgquarrel#38]
It would be great to add the functionality to compare only a specific schema.

**Comment by hyperknot** [comment]
Also, it'd be great to exclude specific schemas from comparison. Best would be support for something like
```
exclude-schema = tmp*
```

**Comment by banek13** [comment]
would be very usefull to have such feature

**Comment by eulerto** [comment]
Commit 72148419a1c3efc5996af004ab83b05ae392c5c9 added options to filter by schemas.
