### ISSUE TITLE
pg_proc on 11 dont have proiswindow

### ISSUE THREAD

**Issue by jeleniste** [eulerto/pgquarrel#57]
It is implemented in prokind enum. Adding this into function.c should solve this

`        if (PQserverVersion(c) > 10000)                                         
        {                                                                       
                res = PQexec(c,                                                 
                                         "SELECT p.oid, nspname, proname, proretset, prosrc, pg_get_function_arguments(p.oid) as funcargs, pg_get_function_identity_arguments(p.oid) as funciargs, pg_get_function_result(p.oid) as funcresult, prokind = 'w' proiswindow, provolatile, proisstrict, prosecdef, proleakproof, array_to_string(proconfig, ',') AS proconfig, proparallel, procost, prorows, (SELECT lanname FROM pg_language WHERE oid = prolang) AS lanname, obj_description(p.oid, 'pg_proc') AS description, pg_get_userbyid(proowner) AS proowner, proacl FROM pg_proc p INNER JOIN pg_namespace n ON (n.oid = p.pronamespace) WHERE n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' AND NOT EXISTS(SELECT 1 FROM pg_depend d WHERE p.oid = d.objid AND d.deptype = 'e') ORDER BY nspname, proname, pg_get_function_identity_arguments(p.oid)");
        }  `

**Comment by eulerto** [comment]
Done in commit bc3da6835efba99dfa0d759515cd1f317d3c7f45
