### ISSUE TITLE
Unterminated string with role name

### ISSUE THREAD

**Issue by grzegorzk** [eulerto/pgquarrel#67]
I found that `GRANT USAGE ON SCHEMA foo TO "role-1";` is rendered in a weird way, looks like pgquarrel is trying to escape double quotes and does it in incomplete way like this: `GRANT USAGE ON SCHEMA foo TO "\"role-1\";`

In cases like this it should be rendered like this: `GRANT USAGE ON SCHEMA foo TO "role-1";`

**Comment by grzegorzk** [comment]
I fixed this within pull request !63

**Comment by eulerto** [comment]
commit cff4f0b90b728e483400d2ba0e53eece524208f2 fixes this issue.
