### ISSUE TITLE
Accepted password can't have more than 8 characters

### ISSUE THREAD

**Issue by nicolasboulay** [eulerto/pgquarrel#72]
It's a bug in quarrel.c

sizeof(prompt_password) will always return 8 in 64 bits environment, because prompt_password is an pointer and not a static array.

Use 100 as hard coded value. I try with "char prompt_password[100];", it works, but the string will not be valid outside of the scope of the function.

**Comment by eulerto** [comment]
Fixed at commit 12698abce6bd91faecc6c0f73b078cc147674139.
