### ISSUE TITLE
Document password option

### ISSUE THREAD

**Issue by hyperknot** [eulerto/pgquarrel#77]
OK, just by pure luck I figured out that if I add a password = ... option to the config file it works. Please document this, as long as this is the right way.

**Comment by eulerto** [comment]
Read [libpq](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) documentation. You can include `password` in connection string or connection URI (you don't need to add the pgquarrel parameter `password` ). I'll add a hint about using dbname to specify connection strings or connections URIs.

**Comment by eulerto** [comment]
Documentation added in commit a256969a18b90b571aed87b6d7ba6b6b4d5728d4
