### ISSUE TITLE
query failed: ERROR:  syntax error at or near "AS"

### ISSUE THREAD

**Issue by hyperknot** [eulerto/pgquarrel#79]
I've enabled -v -v mode but I get the following:
```
ERROR query failed: ERROR:  syntax error at or near "AS"
LINE 1: ...isagg THEN 'a' WHEN proiswindow THEN 'w' ELSE 'f' AS prokind...
```

How can I see what is even LINE 1 in full?

**Comment by eulerto** [comment]
Ops. That's a bug. I fixed it at commit a824029c261ffcb66d9d55f6195f7360ddda4ea7
