### ISSUE TITLE
getCheckConstraints (table.c) - Segmentation fault

### ISSUE THREAD

**Issue by rafaelsagastume** [eulerto/pgquarrel#84]
In the getCheckConstraints (table.c) method, the PQLTable parameter receives the list of tables from both the source and target, t-> kind generates a (Segmentation fault).

> Program received signal SIGSEGV, Segmentation fault.
0x00000000080415fb in getCheckConstraints (c=0x807b6d0, t=0x0, n=0)
    at /mnt/c/Users/rgarcia/Desktop/Arch/repos/pgquarrel/src/table.c:470
470             if (PGQ_IS_REGULAR_OR_PARTITIONED_TABLE(t->kind))

>

**Comment by eulerto** [comment]
PR #86 fixes it.
